### ISSUE TITLE
Boss Parry Haste

### ISSUE THREAD

**Issue by Jinnai** [mobmentality67/mobmentality67.github.io#32]
Usually when selecting `Boss Parry Haste: No` the DTPS and the iterations that resulted in death go **down**. However with some configurations the opposite happens, which doesn't make sense?

It seems very pronounced with a configuration like this:
Buffs: Full Stomp active and all defensive Boss Buffs & Debuffs enabled
Boss Damage (If Active Tank): 14000
Boss Swing Timer (If Active Tank): 1.0
Add 50% Damage Offhand Swing (No DW Penalty): Yes

Changing Boss Parry from Yes to No increases iterations that result in death by around 6% for this config.

**Comment by mobmentality67** [comment]
This has taken a lot more debugging than I expected -- here's the long answer:
- The whole sim is an event driven loop, so events are checked each time there's either a player outgoing attack or an incoming boss attack
- The boss special implementation was not given an independent timer to drive the loop -- instead, boss specials are checked when an incoming attack is rolled
- The toggle swap implementation is sensitive to exactly where you are in a 36 boss "split" to determine how to handle the duration of the stomp and whether or not you are healed. Since boss specials are checked on the boundary of incoming boss swings, small variation in boss swing timer checks can result in widely different dangerousness of the stomp (can force it into the "take the whole stomp" bucket or not). 
- The stomp that goes off at 210 seconds is a stomp that's likely to fall into that bucket -- small variance in swing timers can force it to be either a 6 second duration with no initial "heal" for a swap, or a 2 second duration stomp with a heal before and after (other tank eats it). Enabling parry haste often forces the swing to fall into the later split, where the tank is healed before and after
The short answer is, the Brutallus "toggle" stomp implementation doesn't work well with parry haste, so don't enable it. I can help remedy this by randomizing the timer/CD of stomp by +/- 2 seconds and potentially by adding a new loop driver variable for boss specials

**Comment by mobmentality67** [comment]
For now, just not using parry haste with Brutallus' stomp abilities should cause the expected behavior in all cases. However, I'll leave this issue open until I get a "fix" that makes boss specials less sensitive to small variation in timing

**Comment by mobmentality67** [comment]
Added variance to boss specials -- https://github.com/mobmentality67/mobmentality67.github.io/commit/2fb06fbfafe2cdb5bea5743f577a6d3792deea20. This should result in avoiding these extremely narrow windows of variance having such big effect.
